baseURL: https://jaswdr.dev/
title: "Jonathan Schweder"
locale: en-us
defaultContentLanguage: en

disableKinds: ["taxonomy", "term", "section", "page", "RSS"]

params:
  posthog:
    apiKey: phc_4gAFRm1jftCJsx1fCyf3zewyNx7Py6QA9ILKj0H8S1f
    host: /ingest
