baseURL: https://jaswdr.dev/
languageCode: en-us
title: Jonathan Schweder
theme: "blog-theme"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: false

# Enable Google Analytics
googleAnalytics: UA-173591496-1

# Enable Disqus forum
disqusShortname: jaswdr-dev

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Github Repo URL. This is used to add "Improve This Page" button
  gitRepo: https://github.com/jaswdr/blog

  # Background image
  background: "images/background.jpg"

  # Logo
  logo:
    main: /assets/images/logo.png
    inverted: /assets/images/logo-inverted.png

  # Copyright
  copyright: © Jonathan Schweder 2020 Copyright.

  # Author info
  author:
    name: "Jonathan Schweder"
    nickname: "jaswdr"
    image: "images/avatar.png"
    contactInfo:
      email: "jonathanschweder@gmail.com"
    summary:
    - I am a Developer
    - I work with Python and Linux

  # Disable blog post (for now)
  enableBlogPost: false

  # Newsletter
  newsletter:
    enable: false
