baseURL: https://jaswdr.dev/
title: "Jonathan Schweder"
locale: en-us
defaultContentLanguage: en

disableKinds: ["taxonomy", "term", "section", "page", "RSS", "sitemap"]

outputFormats:
  llms:
    mediaType: text/plain
    baseName: llms
    isPlainText: true
  cv:
    mediaType: text/plain
    baseName: cv
    isPlainText: true
  resume:
    mediaType: application/json
    baseName: cv
    isPlainText: true

outputs:
  home: [HTML, llms, cv, resume]
