name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.89.4
          TARGET_REPO: jaswdr/blog
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUGO_ARGS: '-t PaperMod --minify'
          CNAME: jaswdr.github.io
