name: hugo-build

on: push

jobs:
  hugo:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Hugo Build
        uses: jakejarvis/hugo-build-action@90a6d4905b03f9462d03e75066b19cf39b2bd47b
        
