name: hugo-build

on: push

jobs:
  hugo:
    name: Hugo build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: latest # optional, default is latest
          extended: true # optional, default is false
        
